<?php
declare(strict_types=1);
if($argc<4){fwrite(STDERR,"Usage: php verify_r17_migration.php <r17_dir> <db_path> <ordinary_user_count>\n");exit(64);}
$r17Dir=rtrim($argv[1],'/');$dbPath=$argv[2];$userCount=(int)$argv[3];
if(!in_array('sqlite',PDO::getAvailableDrivers(),true)){fwrite(STDERR,"pdo_sqlite unavailable\n");exit(69);}require $r17Dir.'/config.php';
$pdo=new PDO('sqlite:'.$dbPath,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$pdo->exec('PRAGMA foreign_keys=ON');
$before=['users'=>(int)$pdo->query('SELECT COUNT(*) FROM users')->fetchColumn(),'conversations'=>(int)$pdo->query('SELECT COUNT(*) FROM conversations')->fetchColumn(),'messages'=>(int)$pdo->query('SELECT COUNT(*) FROM messages')->fetchColumn(),'memories'=>(int)$pdo->query('SELECT COUNT(*) FROM memories')->fetchColumn()];
$preCols=array_map(static fn($r)=>(string)$r['name'],$pdo->query('PRAGMA table_info(users)')->fetchAll());if(in_array('managed_user',$preCols,true))throw new RuntimeException('Fixture is not an R16 predecessor: managed_user already exists.');
migrate_schema($pdo,true);$firstState=r17_managed_user_state($pdo);migrate_schema($pdo,true);$secondState=r17_managed_user_state($pdo);
$after=['users'=>(int)$pdo->query('SELECT COUNT(*) FROM users')->fetchColumn(),'conversations'=>(int)$pdo->query('SELECT COUNT(*) FROM conversations')->fetchColumn(),'messages'=>(int)$pdo->query('SELECT COUNT(*) FROM messages')->fetchColumn(),'memories'=>(int)$pdo->query('SELECT COUNT(*) FROM memories')->fetchColumn()];if($before!==$after)throw new RuntimeException('R16→R17 migration changed predecessor row counts: '.json_encode(['before'=>$before,'after'=>$after]));
$present=array_map('strval',$pdo->query("SELECT name FROM sqlite_master WHERE type='table'")->fetchAll(PDO::FETCH_COLUMN));foreach(['assistant_rules','assistant_rule_versions','memory_exclusions','help_requests'] as $t){if(!in_array($t,$present,true))throw new RuntimeException('Missing R17 table after migration: '.$t);}
$cols=array_map(static fn($r)=>(string)$r['name'],$pdo->query('PRAGMA table_info(users)')->fetchAll());foreach(['managed_user','managed_user_designated_at','retired_at','retired_reason'] as $c){if(!in_array($c,$cols,true))throw new RuntimeException('Missing R17 users column: '.$c);}
$memoryCols=array_map(static fn($r)=>(string)$r['name'],$pdo->query('PRAGMA table_info(memories)')->fetchAll());foreach(['confidence','evidence_count','first_observed_at','last_observed_at','automatic','pinned','supersedes_id','superseded_by_id','fingerprint'] as $c){if(!in_array($c,$memoryCols,true))throw new RuntimeException('Missing R17 memories column: '.$c);}
if((string)$pdo->query("SELECT content FROM messages WHERE id='msg-admin-r16'")->fetchColumn()!=='R16 migration preservation marker')throw new RuntimeException('Predecessor message content was not preserved.');
$mem=$pdo->query("SELECT content,fingerprint,evidence_count,first_observed_at,last_observed_at FROM memories WHERE id='mem-admin-r16'")->fetch();if(!is_array($mem)||$mem['content']!=='Preserve this R16 memory exactly'||trim((string)$mem['fingerprint'])===''||(int)$mem['evidence_count']<1||trim((string)$mem['first_observed_at'])===''||trim((string)$mem['last_observed_at'])==='')throw new RuntimeException('R16 memory was not preserved/enriched correctly.');
$ordinary=(int)$pdo->query("SELECT COUNT(*) FROM users WHERE role='user' AND disabled=0 AND account_state IN ('active','pending_enrolment','auth_upgrade_required')")->fetchColumn();$managed=(int)$pdo->query("SELECT COUNT(*) FROM users WHERE role='user' AND managed_user=1")->fetchColumn();$selection=(string)r17_meta_get($pdo,'r17_managed_user_selection_required','');$state=(string)($secondState['state']??'');if($ordinary!==$userCount)throw new RuntimeException("Ordinary-user count changed: expected $userCount got $ordinary");
if($userCount===0){if($state!=='unassigned'||$managed!==0||$selection!=='0')throw new RuntimeException('0-user deterministic managed-user state failed.');}elseif($userCount===1){if($state!=='assigned'||$managed!==1||$selection!=='0'||(string)r17_meta_get($pdo,'r17_managed_user_id','')!=='user-r16-1')throw new RuntimeException('1-user deterministic managed-user state failed.');}else{if($state!=='selection_required'||$managed!==0||$selection!=='1'||count((array)($secondState['candidates']??[]))!==$userCount)throw new RuntimeException('2+-user deterministic selection-required state failed.');}
if(($firstState['state']??null)!==($secondState['state']??null))throw new RuntimeException('Migration is not idempotent across managed-user reconciliation.');$integrity=strtolower((string)$pdo->query('PRAGMA integrity_check')->fetchColumn());$fk=$pdo->query('PRAGMA foreign_key_check')->fetchAll();if($integrity!=='ok'||$fk)throw new RuntimeException('Post-migration SQLite integrity failed.');
$out=['case'=>'r16_to_r17_'.$userCount.'_ordinary_users','result'=>'PASS','before'=>$before,'after'=>$after,'managed_user_state'=>$secondState['state'],'managed_user_count'=>$managed,'selection_required'=>$selection,'memory_fingerprint_backfilled'=>true,'idempotent'=>true,'integrity'=>$integrity,'foreign_key_violations'=>count($fk),'database_sha256'=>hash_file('sha256',$dbPath)];echo json_encode($out,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),"\n";
